#!/bin/bash

# create private key
openssl genrsa -out server.pem 2048

#create signing request
openssl req -new -key server.pem -out server.csr -config openssl.cnf

# sign certificate signing request
openssl x509 -req -days 3650 -in server.csr -signkey server.pem -out server.crt -extensions v3_req -extfile openssl.cnf

#Export the Certificate in pfx format:
openssl pkcs12 -export -in server.crt -inkey server.pem -out server.pfx

# to install the certificate
certutil -d sql:$HOME/.pki/nssdb -A -t "P,," -n craig -i server.crt

#convert to der for android(maybe)
#openssl x509 -inform PEM -outform DER -in CA.crt -out CA.der.crt

cp server.crt ../bin/cert.pem 
cp server.pem ../bin/key.pem

cp server.crt ../Docker/server.crt
cp server.pem ../Docker/server.pem
