#!/bin/bash
#https://medium.com/@tbusser/creating-a-browser-trusted-self-signed-ssl-certificate-2709ce43fd15

openssl genrsa -des3 -out rootCA.key 2048
openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024  -out rootCA.pem

openssl req -new -nodes -out server.csr -newkey rsa:2048 -keyout server.key
openssl x509 -req -in server.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out server.crt -days 500 -sha256 -extfile v3.ext

openssl pkcs12 -inkey server.key -in server.crt -export -out server.pfx

## Make sure you make the SANs as IP rther than DNS for ip addresses
# chrome does give you a cert error in dev tools!

#convert to der for android(maybe)
#openssl x509 -inform PEM -outform DER -in CA.crt -out CA.der.crt

cp server.crt ../bin/cert.pem 
cp server.key ../bin/key.pem

cp server.crt ../Docker/server.crt
cp server.key ../Docker/server.pem
