CREATE TABLE test1
(
test1 INT PRIMARY KEY AUTO_INCREMENT,
test2 VARCHAR(10),
FOREIGN KEY (artistID) REFERENCES Artist (artistID)
);

CREATE TABLE test2
(
test1 INT PRIMARY KEY AUTO_INCREMENT,
test2 VARCHAR(10),
FOREIGN KEY (albumID) REFERENCES Album (albumID)
);
