INSERT INTO Artist VALUES(NULL,'Avenged Sevenfold', 0, 'Unknown');
INSERT INTO Album VALUES(NULL,'Bat Country',1,'0000',0);
INSERT INTO Song VALUES(NULL,'yc.mp3', 1, '00:00:00', 0, 0, 'Avenged Sevenfold/Bat Country/yc.mp3', ''); 
INSERT INTO Artist VALUES(NULL,'test1', 0, 'Unknown');
INSERT INTO Album VALUES(NULL,'testalbum',2,'0000',0);
INSERT INTO Song VALUES(NULL,'7 - Kiss It Goodbye.mp3', 2, '00:00:00', 0, 0, 'test1/testalbum/7 - Kiss It Goodbye.mp3', ''); 
INSERT INTO Artist VALUES(NULL,'NickleBack', 0, 'Unknown');
INSERT INTO Album VALUES(NULL,'Here And Now',3,'0000',0);
INSERT INTO Song VALUES(NULL,'Midnight Queen.mp3', 3, '00:00:00', 0, 0, 'NickleBack/Here And Now/Midnight Queen.mp3', ''); 
INSERT INTO Album VALUES(NULL,'All the Right Reason',3,'0000',0);
INSERT INTO Song VALUES(NULL,'sureShot', 4, '00:00:00', 0, 0, 'NickleBack/All the Right Reason/sureShot', ''); 
INSERT INTO Artist VALUES(NULL,'Nickelback', 0, 'Unknown');
INSERT INTO Album VALUES(NULL,'All the Right Reasons',4,'0000',0);
INSERT INTO Song VALUES(NULL,'animals.mp3', 5, '00:00:00', 0, 0, 'Nickelback/All the Right Reasons/animals.mp3', ''); 
INSERT INTO Song VALUES(NULL,'far away.mp3', 5, '00:00:00', 0, 0, 'Nickelback/All the Right Reasons/far away.mp3', ''); 
INSERT INTO Album VALUES(NULL,'Here And Now',4,'0000',0);
INSERT INTO Song VALUES(NULL,'biffy clyro - Joy.Discovery.Invention.mp3', 6, '00:00:00', 0, 0, 'Nickelback/Here And Now/biffy clyro - Joy.Discovery.Invention.mp3', ''); 
INSERT INTO Album VALUES(NULL,'bob',4,'0000',0);
INSERT INTO Song VALUES(NULL,'11 - Don\'t Ever Let It End.mp3', 7, '00:00:00', 0, 0, 'Nickelback/bob/11 - Don\'t Ever Let It End.mp3', ''); 
INSERT INTO Artist VALUES(NULL,'iron maiden', 0, 'Unknown');
INSERT INTO Album VALUES(NULL,'ironmaindenAlbum',5,'0000',0);
INSERT INTO Song VALUES(NULL,'11 - Don\'t Ever Let It End.mp3', 8, '00:00:00', 0, 0, 'iron maiden/ironmaindenAlbum/11 - Don\'t Ever Let It End.mp3', ''); 
