#!/bin/bash

config="Debug"

if [ -z "$1" ]
then
      echo "Defaulting to building debug"
else
      config=$1
      echo "Building $config"
fi

cmake -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang-6.0 -DCMAKE_BUILD_TYPE=$config -DCMAKE_INSTALL_PREFIX=/home/Arsehole CMakeLists.txt
make -j8 install